from __future__ import annotations

import json
import tarfile
from pathlib import Path

import pytest
from prepare_hf_release import (
    REPO_ID,
    build_deterministic_tar,
    canonical_sha256,
    compact_eartts_report,
    compact_nano_report,
    inventory,
    verify_staged_release,
)
from upload_hf import HF_AUTOGENERATED_FILES, remote_file_inventory, upload_and_verify


def _release(root: Path) -> dict:
    (root / "nano").mkdir(parents=True)
    (root / "nano/model.safetensors").write_bytes(b"weights")
    files = inventory(root)
    manifest = {
        "schema": 1,
        "kind": "nemotron_voicechat_dgx_spark_hf_release",
        "repository": REPO_ID,
        "derived_from_ea": False,
        "files": files,
        "files_sha256": canonical_sha256(files),
    }
    manifest["release_sha256"] = canonical_sha256(manifest)
    (root / "manifests").mkdir()
    (root / "manifests/release.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return manifest


def test_staged_release_manifest_covers_every_payload(tmp_path: Path) -> None:
    expected = _release(tmp_path)
    assert verify_staged_release(tmp_path)["release_sha256"] == expected["release_sha256"]
    (tmp_path / "unexpected").write_bytes(b"x")
    with pytest.raises(ValueError, match="differs"):
        verify_staged_release(tmp_path)


def test_uploader_resume_cache_is_not_release_payload(tmp_path: Path) -> None:
    expected = _release(tmp_path)
    cache = tmp_path / ".cache/huggingface/upload"
    cache.mkdir(parents=True)
    (cache / "resume-state").write_text("tool-owned")
    assert verify_staged_release(tmp_path)["release_sha256"] == expected["release_sha256"]


def test_dry_run_validates_without_network(tmp_path: Path) -> None:
    expected = _release(tmp_path)
    result = upload_and_verify(
        tmp_path,
        revision="main",
        private=False,
        dry_run=True,
        num_workers=1,
    )
    assert result["repo_id"] == REPO_ID
    assert result["release_sha256"] == expected["release_sha256"]
    assert result["dry_run"] is True


def test_portable_reports_drop_host_paths_and_elapsed_time() -> None:
    nano = compact_nano_report(
        {
            "status": "complete",
            "source": "/home/user/model",
            "elapsed_seconds": 12.3,
            "runtime": {"image": "local/private", "packages": {"torch": "pinned"}},
            "calibration": {"roots": ["/calibration/0"], "calls": 3},
            "evaluation": {"roots": ["/evaluation/0"], "calls": 1},
            "runs": [{"layer_metrics": [{"relative_rmse": 0.01}]}],
        }
    )
    eartts = compact_eartts_report(
        {
            "status": "complete",
            "source": "/home/user/model",
            "output": "/tmp/output",
            "elapsed_seconds": 3.0,
        },
        {"runs": 2, "byte_identical": True},
    )
    encoded = json.dumps({"nano": nano, "eartts": eartts})
    assert "/home/" not in encoded
    assert "/tmp/" not in encoded
    assert "elapsed_seconds" not in encoded
    assert "local/private" not in encoded
    assert nano["runtime"]["packages"] == {"torch": "pinned"}
    assert eartts["reproducibility"]["byte_identical"] is True


def test_remote_inventory_accepts_hugging_face_lfs_objects() -> None:
    class LfsMetadata:
        sha256 = "abc123"

    class Sibling:
        rfilename = "nano/model.safetensors"
        size = 7
        lfs = LfsMetadata()

    class Info:
        siblings = [Sibling()]

    assert remote_file_inventory(Info()) == {
        "nano/model.safetensors": {"bytes": 7, "sha256": "abc123"}
    }
    assert HF_AUTOGENERATED_FILES == {".gitattributes"}


def test_replay_archive_is_deterministic_and_normalized(tmp_path: Path) -> None:
    source = tmp_path / "source"
    source.mkdir()
    first = source / "b.pt"
    second = source / "a.json"
    first.write_bytes(b"tensor")
    second.write_text("{}\n")
    first.chmod(0o600)
    one = tmp_path / "one.tar"
    two = tmp_path / "two.tar"
    files = [(first, "calibration/0/b.pt"), (second, "calibration/0/a.json")]
    build_deterministic_tar(files, one)
    first.touch()
    build_deterministic_tar(list(reversed(files)), two)
    assert one.read_bytes() == two.read_bytes()
    with tarfile.open(one) as archive:
        members = archive.getmembers()
    assert [item.name for item in members] == [
        "calibration/0/a.json",
        "calibration/0/b.pt",
    ]
    assert all(item.uid == item.gid == item.mtime == 0 for item in members)
    assert all(item.mode == 0o644 for item in members)
