#!/usr/bin/env python3
"""Dry-run, upload, and read back the one approved Hugging Face model release."""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path

from huggingface_hub import HfApi
from prepare_hf_release import REPO_ID, sha256_file, verify_staged_release

HF_AUTOGENERATED_FILES = frozenset({".gitattributes"})


def remote_file_inventory(info) -> dict[str, dict]:
    result = {}
    for item in info.siblings or []:
        lfs = item.lfs or {}
        if isinstance(lfs, dict):
            lfs_sha256 = lfs.get("sha256")
        else:
            lfs_sha256 = getattr(lfs, "sha256", None)
        result[item.rfilename] = {
            "bytes": item.size,
            "sha256": lfs_sha256,
        }
    return result


def upload_and_verify(
    root: Path,
    *,
    revision: str,
    private: bool,
    dry_run: bool,
    num_workers: int,
) -> dict:
    manifest = verify_staged_release(root)
    summary = {
        "repo_id": REPO_ID,
        "revision": revision,
        "release_sha256": manifest["release_sha256"],
        "file_count": len(manifest["files"]) + 1,
        "payload_bytes": sum(item["bytes"] for item in manifest["files"]),
        "dry_run": dry_run,
    }
    if dry_run:
        return summary

    api = HfApi()
    api.create_repo(REPO_ID, repo_type="model", private=private, exist_ok=True)
    if revision != "main":
        api.create_branch(REPO_ID, branch=revision, repo_type="model", exist_ok=True)
    api.upload_large_folder(
        repo_id=REPO_ID,
        folder_path=root,
        repo_type="model",
        revision=revision,
        private=private,
        num_workers=num_workers,
    )
    info = api.repo_info(
        REPO_ID,
        repo_type="model",
        revision=revision,
        files_metadata=True,
    )
    with tempfile.TemporaryDirectory(prefix="voicechat-hf-readback-") as temporary:
        readback_root = Path(temporary)
        downloaded = api.hf_hub_download(
            REPO_ID,
            "manifests/release.json",
            repo_type="model",
            revision=info.sha,
            local_dir=readback_root,
            force_download=True,
        )
        if sha256_file(Path(downloaded)) != sha256_file(root / "manifests/release.json"):
            raise RuntimeError("post-upload release manifest read-back mismatch")
        remote = remote_file_inventory(info)
        expected_paths = {item["path"] for item in manifest["files"]} | {
            "manifests/release.json"
        }
        # Hugging Face creates .gitattributes to route large payloads through
        # LFS. It is repository metadata, not release payload, and therefore
        # cannot be present in the signed local release manifest.
        remote_payload_paths = set(remote) - HF_AUTOGENERATED_FILES
        if remote_payload_paths != expected_paths:
            raise RuntimeError("post-upload repository file inventory mismatch")
        for item in manifest["files"]:
            metadata = remote[item["path"]]
            if metadata["bytes"] != item["bytes"]:
                raise RuntimeError(f"post-upload byte count mismatch: {item['path']}")
            remote_sha256 = metadata["sha256"]
            if remote_sha256 is None:
                downloaded = api.hf_hub_download(
                    REPO_ID,
                    item["path"],
                    repo_type="model",
                    revision=info.sha,
                    local_dir=readback_root,
                    force_download=True,
                )
                remote_sha256 = sha256_file(Path(downloaded))
            if remote_sha256 != item["sha256"]:
                raise RuntimeError(f"post-upload SHA-256 mismatch: {item['path']}")
    return {**summary, "immutable_revision": info.sha, "dry_run": False}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("--repo-id", default=REPO_ID, choices=(REPO_ID,))
    parser.add_argument("--revision", default="main")
    parser.add_argument("--private", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--num-workers", type=int, default=4)
    args = parser.parse_args()
    result = upload_and_verify(
        args.root.expanduser().resolve(),
        revision=args.revision,
        private=args.private,
        dry_run=args.dry_run,
        num_workers=args.num_workers,
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
